"""add_contract_builder_models

Revision ID: 13c8688c8ef9
Revises: ff716ba9fbb2
Create Date: 2026-05-15 10:55:40.325282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c8688c8ef9'
down_revision = 'ff716ba9fbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_clause_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tooltip', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_clause_group', schema=None) as batch_op:
        batch_op.create_index('idx_ccg_sort_order', ['sort_order'], unique=False)

    op.create_table('contract_clause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tooltip_short', sa.String(length=300), nullable=True),
    sa.Column('tooltip_long', sa.Text(), nullable=True),
    sa.Column('clause_type', sa.Enum('text', 'textarea', 'number', 'percentage', 'toggle', 'toggle_with_details', 'select', 'date', 'date_range', 'territory', 'duration', 'multi_toggle', name='clausetypeenum'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_enabled_by_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legal_reference', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['contract_clause_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_clause', schema=None) as batch_op:
        batch_op.create_index('idx_cc_group_sort', ['group_id', 'sort_order'], unique=False)

    op.create_table('user_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'final', name='usercontractstatus'), nullable=False),
    sa.Column('pdf_file', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_contract', schema=None) as batch_op:
        batch_op.create_index('idx_uc_user_id', ['user_id'], unique=False)

    op.create_table('user_contract_party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.Enum('physical', 'company', name='partytypeenum'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('pseudonym', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('legal_form', sa.String(length=100), nullable=True),
    sa.Column('capital', sa.String(length=80), nullable=True),
    sa.Column('siren', sa.String(length=20), nullable=True),
    sa.Column('siret', sa.String(length=25), nullable=True),
    sa.Column('rcs', sa.String(length=100), nullable=True),
    sa.Column('legal_rep', sa.String(length=200), nullable=True),
    sa.Column('signatory_title', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['user_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_contract_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['contract_clause.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['user_contract.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'clause_id', name='unique_contract_clause')
    )
    with op.batch_alter_table('user_contract_value', schema=None) as batch_op:
        batch_op.create_index('idx_ucv_contract_id', ['contract_id'], unique=False)

    with op.batch_alter_table('price_change_request', schema=None) as batch_op:
        batch_op.alter_column('old_reference_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('new_reference_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_change_request', schema=None) as batch_op:
        batch_op.alter_column('new_reference_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('old_reference_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('user_contract_value', schema=None) as batch_op:
        batch_op.drop_index('idx_ucv_contract_id')

    op.drop_table('user_contract_value')
    op.drop_table('user_contract_party')
    with op.batch_alter_table('user_contract', schema=None) as batch_op:
        batch_op.drop_index('idx_uc_user_id')

    op.drop_table('user_contract')
    with op.batch_alter_table('contract_clause', schema=None) as batch_op:
        batch_op.drop_index('idx_cc_group_sort')

    op.drop_table('contract_clause')
    with op.batch_alter_table('contract_clause_group', schema=None) as batch_op:
        batch_op.drop_index('idx_ccg_sort_order')

    op.drop_table('contract_clause_group')
    # ### end Alembic commands ###
