"""Ajout des favoris et historique d'écoute

Revision ID: 15a90336eb69
Revises: 49f32fc8fee5
Create Date: 2026-01-06 18:18:52.919669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a90336eb69'
down_revision = '49f32fc8fee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='unique_user_track_favorite')
    )
    op.create_table('listening_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('listened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_file_tree', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_column('archive_file_tree')

    op.drop_table('listening_history')
    op.drop_table('favorite')
    # ### end Alembic commands ###
