"""new Revision columns

Revision ID: 1630b4bc818c
Revises: 88a618a2bac7
Create Date: 2026-03-18 16:51:28.393954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1630b4bc818c'
down_revision = '88a618a2bac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_count', sa.Integer(), nullable=False, server_default=str('0')))
        batch_op.add_column(sa.Column('revision1_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revision2_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revision1_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revision1_delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revision2_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revision2_delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processed_file_revision1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('processed_file_revision2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('stripe_revision1_transfer_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('stripe_revision2_transfer_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_column('stripe_revision2_transfer_id')
        batch_op.drop_column('stripe_revision1_transfer_id')
        batch_op.drop_column('processed_file_revision2')
        batch_op.drop_column('processed_file_revision1')
        batch_op.drop_column('revision2_delivered_at')
        batch_op.drop_column('revision2_requested_at')
        batch_op.drop_column('revision1_delivered_at')
        batch_op.drop_column('revision1_requested_at')
        batch_op.drop_column('revision2_message')
        batch_op.drop_column('revision1_message')
        batch_op.drop_column('revision_count')

    # ### end Alembic commands ###
