"""engineer_view: tracking vues pages ingénieur

Revision ID: 220271cd014f
Revises: f11efd5923a5
Create Date: 2026-07-15 16:45:59.051709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220271cd014f'
down_revision = 'f11efd5923a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineer_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engineer_view', schema=None) as batch_op:
        batch_op.create_index('ix_engineer_view_engineer', ['engineer_id'], unique=False)
        batch_op.create_index('ix_engineer_view_ip_date', ['engineer_id', 'ip_hash', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engineer_view', schema=None) as batch_op:
        batch_op.drop_index('ix_engineer_view_ip_date')
        batch_op.drop_index('ix_engineer_view_engineer')

    op.drop_table('engineer_view')
    # ### end Alembic commands ###
