"""add mixmaster revision colums

Revision ID: 306436f07678
Revises: 89d52a587eeb
Create Date: 2026-03-02 17:31:44.666142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306436f07678'
down_revision = '89d52a587eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('revision_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stripe_revision1_transfer_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('stripe_revision2_transfer_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_column('stripe_revision2_transfer_id')
        batch_op.drop_column('stripe_revision1_transfer_id')
        batch_op.drop_column('revision_count')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
