"""ajout de la colonne is_published

Revision ID: 32aa101646b3
Revises: b8629fcd5337
Create Date: 2025-12-22 17:46:35.406943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32aa101646b3'
down_revision = 'b8629fcd5337'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Ajouter la colonne nullable
    op.add_column(
        'topline',
        sa.Column('is_published', sa.Boolean(), nullable=True)
    )

    # 2. Mettre une valeur par défaut sur les lignes existantes
    op.execute("UPDATE topline SET is_published = FALSE")

    # 3. Rendre la colonne NOT NULL
    op.alter_column(
        'topline',
        'is_published',
        nullable=False
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topline', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
