"""add tooltip_plain to contract_clause

Revision ID: 454727327355
Revises: 5496d22d9fbe
Create Date: 2026-05-16 10:44:22.413338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454727327355'
down_revision = '5496d22d9fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_clause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tooltip_plain', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_clause', schema=None) as batch_op:
        batch_op.drop_column('tooltip_plain')

    # ### end Alembic commands ###
