"""Add detailed artist briefing fields to MixMasterRequest

Revision ID: 49f32fc8fee5
Revises: ca5c5cbf0864
Create Date: 2026-01-05 11:23:23.708868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f32fc8fee5'
down_revision = 'ca5c5cbf0864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brief_vocals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_backing_vocals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_ambiance', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_bass', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_energy_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_references', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_instruments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_percussion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_effects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_structure', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_column('brief_structure')
        batch_op.drop_column('brief_effects')
        batch_op.drop_column('brief_percussion')
        batch_op.drop_column('brief_instruments')
        batch_op.drop_column('brief_references')
        batch_op.drop_column('brief_energy_style')
        batch_op.drop_column('brief_bass')
        batch_op.drop_column('brief_ambiance')
        batch_op.drop_column('brief_backing_vocals')
        batch_op.drop_column('brief_vocals')

    # ### end Alembic commands ###
