"""updated mixmaster with 2 previews

Revision ID: 5370513c7ac1
Revises: f1b2856189a3
Create Date: 2026-02-02 14:12:27.022000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5370513c7ac1'
down_revision = 'f1b2856189a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_file_preview_full', sa.String(length=200), nullable=True))

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index('idx_track_composer', ['composer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index('idx_track_composer')

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_column('processed_file_preview_full')

    # ### end Alembic commands ###
