"""add_example_text_to_contract_clause

Revision ID: 5496d22d9fbe
Revises: 13c8688c8ef9
Create Date: 2026-05-15 12:54:38.571768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5496d22d9fbe'
down_revision = '13c8688c8ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_clause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_clause', schema=None) as batch_op:
        batch_op.drop_column('example_text')

    # ### end Alembic commands ###
