"""Add mixmaster pricing services system

Revision ID: 60815a044d6a
Revises: a39485e1333c
Create Date: 2026-01-04 20:17:01.425996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60815a044d6a'
down_revision = 'a39485e1333c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_cleaning', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('service_effects', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('service_artistic', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('service_mastering', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_separated_stems', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('artist_message', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mixmaster_price_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mixmaster_price_min', sa.Float(), nullable=True))
        batch_op.drop_column('mixmaster_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mixmaster_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('mixmaster_price_min')
        batch_op.drop_column('mixmaster_price_max')

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_column('artist_message')
        batch_op.drop_column('has_separated_stems')
        batch_op.drop_column('service_mastering')
        batch_op.drop_column('service_artistic')
        batch_op.drop_column('service_effects')
        batch_op.drop_column('service_cleaning')

    # ### end Alembic commands ###
