"""marketing: consentement opt-in + campagnes + destinataires

Revision ID: 6d617233132b
Revises: 7a8d60ef76b2
Create Date: 2026-07-14 19:15:39.851613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d617233132b'
down_revision = '7a8d60ef76b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('sent_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('failed_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("segment IN ('buyers','favorites','listeners','all')", name='ck_campaign_segment'),
    sa.CheckConstraint('recipient_count >= 0 AND sent_count >= 0 AND failed_count >= 0', name='ck_campaign_counts_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    with op.batch_alter_table('marketing_campaign', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_dispatch', ['status', 'scheduled_for'], unique=False)
        batch_op.create_index('idx_campaign_owner_status', ['owner_id', 'status'], unique=False)

    op.create_table('campaign_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_recipient')
    )
    with op.batch_alter_table('campaign_recipient', schema=None) as batch_op:
        batch_op.create_index('idx_recipient_user_sent', ['user_id', 'sent_at'], unique=False)

    # server_default='false' — DOUBLEMENT nécessaire :
    #  1. techniquement, la colonne est NOT NULL et la table user est peuplée ;
    #  2. juridiquement, le consentement ne se présume pas. Un default à 'true'
    #     opterait rétroactivement toute la base dans de la prospection commerciale
    #     sans le moindre acte positif des utilisateurs. Ne jamais l'inverser.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketing_opt_in', sa.Boolean(),
                                      nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('marketing_opt_in_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('marketing_opt_in_at')
        batch_op.drop_column('marketing_opt_in')

    with op.batch_alter_table('campaign_recipient', schema=None) as batch_op:
        batch_op.drop_index('idx_recipient_user_sent')

    op.drop_table('campaign_recipient')
    with op.batch_alter_table('marketing_campaign', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_owner_status')
        batch_op.drop_index('idx_campaign_dispatch')

    op.drop_table('marketing_campaign')
    # ### end Alembic commands ###
