"""add listen_events table

Revision ID: 731a20ee0147
Revises: 3ba30de38760
Create Date: 2026-05-18 12:32:34.933709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731a20ee0147'
down_revision = '3ba30de38760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listen_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('duration_listened', sa.Float(), nullable=False),
    sa.Column('track_duration', sa.Float(), nullable=False),
    sa.Column('completion_ratio', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listen_events', schema=None) as batch_op:
        batch_op.create_index('ix_listen_event_track', ['track_id'], unique=False)
        batch_op.create_index('ix_listen_event_user', ['user_id'], unique=False)
        batch_op.create_index('ix_listen_event_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listen_events', schema=None) as batch_op:
        batch_op.drop_index('ix_listen_event_user_created')
        batch_op.drop_index('ix_listen_event_user')
        batch_op.drop_index('ix_listen_event_track')

    op.drop_table('listen_events')
    # ### end Alembic commands ###
