"""added notification model

Revision ID: 764da85876cb
Revises: e9c59eb9f99d
Create Date: 2026-01-30 16:17:52.606633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764da85876cb'
down_revision = 'e9c59eb9f99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('idx_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_user_unread', ['user_id', 'is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('idx_user_unread')
        batch_op.drop_index('idx_user_created')

    op.drop_table('notification')
    # ### end Alembic commands ###
