"""promo codes: table, targets, redemptions + discount columns

Revision ID: 7a8d60ef76b2
Revises: c7e4b2a19f06
Create Date: 2026-07-14 14:55:13.333064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8d60ef76b2'
down_revision = 'c7e4b2a19f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('applies_to_all', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('once_per_user', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(code) BETWEEN 4 AND 15', name='ck_promo_code_length'),
    sa.CheckConstraint('max_redemptions IS NULL OR max_redemptions > 0', name='ck_promo_max_redemptions_positive'),
    sa.CheckConstraint('percent IN (10, 20, 30, 50, 70)', name='ck_promo_percent_allowed'),
    sa.CheckConstraint('redemption_count >= 0', name='ck_promo_redemption_count_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'code', name='uq_promo_code_owner_code')
    )
    with op.batch_alter_table('promo_code', schema=None) as batch_op:
        batch_op.create_index('idx_promo_owner_active', ['owner_id', 'is_active'], unique=False)

    op.create_table('promo_code_service',
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promo_code_id', 'service_key')
    )
    op.create_table('promo_code_track',
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promo_code_id', 'track_id')
    )
    op.create_table('promo_code_redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('mixmaster_request_id', sa.Integer(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percent_applied', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_redemption_discount_positive'),
    sa.CheckConstraint('net_amount >= 0', name='ck_redemption_net_positive'),
    sa.ForeignKeyConstraint(['mixmaster_request_id'], ['mixmaster_request.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_code_redemption', schema=None) as batch_op:
        batch_op.create_index('idx_redemption_promo_user', ['promo_code_id', 'user_id'], unique=False)

    # discount_amount est NOT NULL : les lignes déjà en base (achats antérieurs
    # aux codes promo) ont besoin d'un server_default pour que l'ALTER passe.
    # gross_price reste NULL sur l'historique : on ne connaît pas rétroactivement
    # un « prix catalogue » distinct du prix payé, et l'inventer fausserait la compta.
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gross_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_mixmaster_request_promo_code', 'promo_code',
                                    ['promo_code_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gross_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_purchase_promo_code', 'promo_code',
                                    ['promo_code_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_promo_code', type_='foreignkey')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('gross_price')
        batch_op.drop_column('promo_code_id')

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mixmaster_request_promo_code', type_='foreignkey')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('gross_price')
        batch_op.drop_column('promo_code_id')

    with op.batch_alter_table('promo_code_redemption', schema=None) as batch_op:
        batch_op.drop_index('idx_redemption_promo_user')

    op.drop_table('promo_code_redemption')
    op.drop_table('promo_code_track')
    op.drop_table('promo_code_service')
    with op.batch_alter_table('promo_code', schema=None) as batch_op:
        batch_op.drop_index('idx_promo_owner_active')

    op.drop_table('promo_code')
    # ### end Alembic commands ###
