"""Added user types and mix/master rules

Revision ID: a39485e1333c
Revises: 09c82763aeca
Create Date: 2026-01-02 11:18:25.273910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a39485e1333c'
down_revision = '09c82763aeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Obtenir une connexion pour vérifier si les colonnes existent
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Vérifier les colonnes existantes dans mixmaster_request
    mixmaster_cols = [col['name'] for col in inspector.get_columns('mixmaster_request')]

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        if 'reference_file' not in mixmaster_cols:
            batch_op.add_column(sa.Column('reference_file', sa.String(length=200), nullable=True))
        if 'accepted_at' not in mixmaster_cols:
            batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        if 'rejected_at' not in mixmaster_cols:
            batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        if 'completed_at' not in mixmaster_cols:
            batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        if 'approved_at' in mixmaster_cols:
            batch_op.drop_column('approved_at')

    # Vérifier les colonnes existantes dans user
    user_cols = [col['name'] for col in inspector.get_columns('user')]

    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'user_type_selected' not in user_cols:
            batch_op.add_column(
                sa.Column('user_type_selected', sa.Boolean(), nullable=False, server_default=sa.false())
            )
        if 'is_artist' not in user_cols:
            batch_op.add_column(
                sa.Column('is_artist', sa.Boolean(), nullable=False, server_default=sa.false())
            )
        if 'is_beatmaker' not in user_cols:
            batch_op.add_column(
                sa.Column('is_beatmaker', sa.Boolean(), nullable=False, server_default=sa.false())
            )
        if 'is_mix_engineer' not in user_cols:
            batch_op.add_column(
                sa.Column('is_mix_engineer', sa.Boolean(), nullable=False, server_default=sa.false())
            )
        if 'mixmaster_sample_submitted' not in user_cols:
            batch_op.add_column(
                sa.Column('mixmaster_sample_submitted', sa.Boolean(), nullable=False, server_default=sa.false())
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mixmaster_sample_submitted')
        batch_op.drop_column('is_mix_engineer')
        batch_op.drop_column('is_beatmaker')
        batch_op.drop_column('is_artist')
        batch_op.drop_column('user_type_selected')

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('accepted_at')
        batch_op.drop_column('reference_file')

    # ### end Alembic commands ###
