"""Add MixMaster module: MixMasterRequest model and User engineer fields

Revision ID: a736effaeb49
Revises: 32aa101646b3
Create Date: 2026-01-01 19:13:37.041075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a736effaeb49'
down_revision = '32aa101646b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixmaster_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('original_file', sa.String(length=200), nullable=False),
    sa.Column('processed_file', sa.String(length=200), nullable=True),
    sa.Column('processed_file_preview', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('remaining_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('engineer_revenue', sa.Float(), nullable=False),
    sa.Column('stripe_deposit_payment_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_final_payment_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_deposit_transfer_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_final_transfer_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_mixmaster_engineer',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )
        batch_op.add_column(sa.Column('mixmaster_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mixmaster_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mixmaster_sample_raw', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mixmaster_sample_processed', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mixmaster_sample_processed')
        batch_op.drop_column('mixmaster_sample_raw')
        batch_op.drop_column('mixmaster_bio')
        batch_op.drop_column('mixmaster_price')
        batch_op.drop_column('is_mixmaster_engineer')

    op.drop_table('mixmaster_request')
    # ### end Alembic commands ###
