"""track contract prices and exclusive sold status

Revision ID: b0cf100bcfd7
Revises: 8e3563578f35
Create Date: 2026-05-20 10:36:19.628027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cf100bcfd7'
down_revision = '8e3563578f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_price_exclusive', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_duration_3y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_duration_5y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_duration_10y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_lifetime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_mechanical', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_public_show', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_arrangement', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_territory_eu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_price_territory_world', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_exclusive_sold', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('exclusive_sold_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('exclusive_buyer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['exclusive_buyer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exclusive_buyer_id')
        batch_op.drop_column('exclusive_sold_at')
        batch_op.drop_column('is_exclusive_sold')
        batch_op.drop_column('contract_price_territory_world')
        batch_op.drop_column('contract_price_territory_eu')
        batch_op.drop_column('contract_price_arrangement')
        batch_op.drop_column('contract_price_public_show')
        batch_op.drop_column('contract_price_mechanical')
        batch_op.drop_column('contract_price_lifetime')
        batch_op.drop_column('contract_price_duration_10y')
        batch_op.drop_column('contract_price_duration_5y')
        batch_op.drop_column('contract_price_duration_3y')
        batch_op.drop_column('contract_price_exclusive')

    # ### end Alembic commands ###
