"""initial migration

Revision ID: b8629fcd5337
Revises: 
Create Date: 2025-12-21 15:42:51.633132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8629fcd5337'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('youtube', sa.String(length=100), nullable=True),
    sa.Column('soundcloud', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_account_status', sa.String(length=50), nullable=True),
    sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(length=200), nullable=False),
    sa.Column('file_mp3', sa.String(length=200), nullable=True),
    sa.Column('file_wav', sa.String(length=200), nullable=True),
    sa.Column('file_stems', sa.String(length=200), nullable=True),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.Column('price_mp3', sa.Float(), nullable=False),
    sa.Column('price_wav', sa.Float(), nullable=False),
    sa.Column('price_stems', sa.Float(), nullable=False),
    sa.Column('sacem_percentage_composer', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('composer_address', sa.String(length=300), nullable=True),
    sa.Column('composer_email', sa.String(length=120), nullable=True),
    sa.Column('composer_credit', sa.String(length=200), nullable=True),
    sa.Column('client_address', sa.String(length=300), nullable=True),
    sa.Column('client_email', sa.String(length=120), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.String(length=200), nullable=False),
    sa.Column('end_date', sa.String(length=200), nullable=False),
    sa.Column('duration_text', sa.String(length=100), nullable=True),
    sa.Column('territory', sa.String(length=200), nullable=False),
    sa.Column('mechanical_reproduction', sa.Boolean(), nullable=False),
    sa.Column('public_show', sa.Boolean(), nullable=False),
    sa.Column('streaming', sa.Boolean(), nullable=False),
    sa.Column('arrangement', sa.Boolean(), nullable=False),
    sa.Column('sacem_percentage_composer', sa.Integer(), nullable=False),
    sa.Column('sacem_percentage_buyer', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('signature_place', sa.String(length=200), nullable=True),
    sa.Column('signature_date', sa.String(length=200), nullable=True),
    sa.Column('contract_file', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['composer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('format_purchased', sa.String(length=20), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('contract_price', sa.Float(), nullable=False),
    sa.Column('track_price', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('composer_revenue', sa.Float(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(length=200), nullable=True),
    sa.Column('contract_file', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('topline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_tag',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_tag')
    op.drop_table('topline')
    op.drop_table('purchase')
    op.drop_table('contract')
    op.drop_table('track')
    op.drop_table('tag')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
