"""device_token_and_push_opt_in

Revision ID: b9e37d82b0aa
Revises: 1a7eb9d24827
Create Date: 2026-09-02 13:33:14.319985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e37d82b0aa'
down_revision = '1a7eb9d24827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('device_token', schema=None) as batch_op:
        batch_op.create_index('idx_device_token_user_active', ['user_id', 'is_active'], unique=False)

    # server_default requis : colonne NOT NULL ajoutée à une table 'user' déjà
    # peuplée (R15) — chaque compte existant démarre à push_opt_in=False, non
    # rétroactif, cf. docs/roadmap.md § Chantier 2 décision 2.3.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_opt_in', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('push_opt_in_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_opt_in_at')
        batch_op.drop_column('push_opt_in')

    with op.batch_alter_table('device_token', schema=None) as batch_op:
        batch_op.drop_index('idx_device_token_user_active')

    op.drop_table('device_token')
    # ### end Alembic commands ###
