"""Add stripe payment intent columns

Revision ID: bbbed61ddd14
Revises: 15a90336eb69
Create Date: 2026-01-07 13:06:23.601032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbed61ddd14'
down_revision = '15a90336eb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_status', sa.String(length=50), nullable=True, server_default='pending'))
        batch_op.create_index('idx_mixmaster_payment_status', ['stripe_payment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_index('idx_mixmaster_payment_status')
        batch_op.drop_column('stripe_payment_status')
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
