"""add idx_track_home composite index

Revision ID: c7425c996797
Revises: f8db8ab8629d
Create Date: 2026-07-02 11:59:32.884647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7425c996797'
down_revision = 'f8db8ab8629d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index('idx_track_home', ['is_approved', 'is_exclusive_sold', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index('idx_track_home')

    # ### end Alembic commands ###
