"""add_legal_compliance_fields

Revision ID: c7e4b2a19f06
Revises: a4f2c9d81e07
Create Date: 2026-07-12 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e4b2a19f06'
down_revision = 'a4f2c9d81e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonogram_producer_attested', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('has_third_party_samples', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('sample_clearance_details', sa.Text(), nullable=True))

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonogram_producer_attested', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('has_third_party_samples', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('sample_clearance_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('buyer_declares_original_lyrics', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('legal_terms_accepted', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('withdrawal_right_waived', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('consent_recorded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('consent_recorded_at')
        batch_op.drop_column('withdrawal_right_waived')
        batch_op.drop_column('legal_terms_accepted')
        batch_op.drop_column('buyer_declares_original_lyrics')
        batch_op.drop_column('sample_clearance_details')
        batch_op.drop_column('has_third_party_samples')
        batch_op.drop_column('phonogram_producer_attested')

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('sample_clearance_details')
        batch_op.drop_column('has_third_party_samples')
        batch_op.drop_column('phonogram_producer_attested')
    # ### end Alembic commands ###
