"""Add PriceChangeRequest table for engineer price modifications

Revision ID: ca5c5cbf0864
Revises: 60815a044d6a
Create Date: 2026-01-05 10:37:07.793537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5c5cbf0864'
down_revision = '60815a044d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('old_price_max', sa.Float(), nullable=False),
    sa.Column('old_price_min', sa.Float(), nullable=False),
    sa.Column('new_price_max', sa.Float(), nullable=False),
    sa.Column('new_price_min', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_change_request')
    # ### end Alembic commands ###
