"""login_event: tracking régularité des connexions

Revision ID: cd41585e0e53
Revises: 220271cd014f
Create Date: 2026-07-15 22:17:04.158205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd41585e0e53'
down_revision = '220271cd014f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'login_date', name='uq_login_event_user_day')
    )
    with op.batch_alter_table('login_event', schema=None) as batch_op:
        batch_op.create_index('ix_login_event_date', ['login_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_event', schema=None) as batch_op:
        batch_op.drop_index('ix_login_event_date')

    op.drop_table('login_event')
    # ### end Alembic commands ###
