"""Add upload and topline token system (premium quotas)

Revision ID: e9c59eb9f99d
Revises: e9c9f4688540
Create Date: 2026-01-17 14:28:03.459716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c59eb9f99d'
down_revision = 'e9c9f4688540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Ajouter les colonnes nullable d'abord, puis mettre les valeurs par défaut
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('premium_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('premium_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upload_track_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_upload_reset', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('topline_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_topline_reset', sa.Date(), nullable=True))

    # Mettre à jour les utilisateurs existants avec valeurs par défaut
    op.execute("UPDATE \"user\" SET is_premium = FALSE WHERE is_premium IS NULL")
    op.execute("UPDATE \"user\" SET upload_track_tokens = 20 WHERE upload_track_tokens IS NULL")
    op.execute("UPDATE \"user\" SET topline_tokens = 5 WHERE topline_tokens IS NULL")
    op.execute("UPDATE \"user\" SET last_upload_reset = CURRENT_DATE WHERE last_upload_reset IS NULL")
    op.execute("UPDATE \"user\" SET last_topline_reset = CURRENT_DATE WHERE last_topline_reset IS NULL")

    # Rendre is_premium NOT NULL maintenant qu'il a des valeurs
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_premium', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_topline_reset')
        batch_op.drop_column('topline_tokens')
        batch_op.drop_column('last_upload_reset')
        batch_op.drop_column('upload_track_tokens')
        batch_op.drop_column('premium_expires_at')
        batch_op.drop_column('premium_since')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
