"""Add OAuth and account status columns

Revision ID: e9c9f4688540
Revises: bbbed61ddd14
Create Date: 2026-01-11 19:22:07.634591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c9f4688540'
down_revision = 'bbbed61ddd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 🧹 SUPPRESSION DES UTILISATEURS EXISTANTS (environnement dev uniquement)
    # Nécessaire car account_status et email_verified sont nullable=False sans default
    # Ordre de suppression important à cause des contraintes de clés étrangères
    op.execute('DELETE FROM purchase')  # Supprimer les achats
    op.execute('DELETE FROM topline')  # Supprimer les toplines
    op.execute('DELETE FROM favorite')  # Supprimer les favoris
    op.execute('DELETE FROM listening_history')  # Supprimer l\'historique d\'écoute
    op.execute('DELETE FROM track_tag')  # Supprimer les relations track-tag
    op.execute('DELETE FROM contract')  # Supprimer les contrats
    op.execute('DELETE FROM mixmaster_request')  # Supprimer les demandes mixmaster
    op.execute('DELETE FROM price_change_request')  # Supprimer les demandes de changement de prix
    op.execute('DELETE FROM track')  # Supprimer les tracks
    op.execute('DELETE FROM "user"')  # Supprimer tous les utilisateurs

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_mixmaster_payment_status'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=50), nullable=False, server_default='pending_completion'))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=True)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.drop_index(batch_op.f('ix_user_account_status'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('account_status')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('google_id')
        batch_op.drop_column('oauth_provider')

    with op.batch_alter_table('mixmaster_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mixmaster_payment_status'), ['stripe_payment_status'], unique=False)

    # ### end Alembic commands ###
