"""license_lifecycle_and_notification_log

Revision ID: f8db8ab8629d
Revises: a8b3c1d9e2f4
Create Date: 2026-07-02 00:05:39.260210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8db8ab8629d'
down_revision = 'a8b3c1d9e2f4'
branch_labels = None
depends_on = None


def _column_exists(table: str, column: str) -> bool:
    from sqlalchemy import inspect as sa_inspect
    inspector = sa_inspect(op.get_bind())
    return column in {c['name'] for c in inspector.get_columns(table)}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('period_key', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id', 'notification_type', 'period_key', name='uq_license_notif_dedup')
    )
    with op.batch_alter_table('license_notification_log', schema=None) as batch_op:
        batch_op.create_index('idx_license_notif_log', ['purchase_id', 'notification_type', 'period_key'], unique=False)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'purchase', ['purchase_id'], ['id'])

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exclusive', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('duration_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_lifetime', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('territory', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('license_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('renewed_from_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('renewed_to_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_purchase_buyer_track', ['buyer_id', 'track_id'], unique=False)
        batch_op.create_index('idx_purchase_license_status', ['license_status'], unique=False)
        batch_op.create_foreign_key(None, 'purchase', ['renewed_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'purchase', ['renewed_from_id'], ['id'])

    if not _column_exists('track', 'is_ai_suggested'):
        with op.batch_alter_table('track', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_ai_suggested', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('track', 'is_ai_suggested'):
        with op.batch_alter_table('track', schema=None) as batch_op:
            batch_op.drop_column('is_ai_suggested')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_purchase_license_status')
        batch_op.drop_index('idx_purchase_buyer_track')
        batch_op.drop_column('renewed_to_id')
        batch_op.drop_column('renewed_from_id')
        batch_op.drop_column('license_status')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('territory')
        batch_op.drop_column('is_lifetime')
        batch_op.drop_column('duration_years')
        batch_op.drop_column('is_exclusive')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('purchase_id')

    with op.batch_alter_table('license_notification_log', schema=None) as batch_op:
        batch_op.drop_index('idx_license_notif_log')

    op.drop_table('license_notification_log')
    # ### end Alembic commands ###
