import { Routes } from '@angular/router';

// Pages (smart — fetch des données)
import { HomeComponent }           from './pages/home/home.component';
import { UploadTrackComponent }         from './components/upload-track/upload-track.component';
import { LoginComponent }          from './pages/auth/login/login.component';
import { TrackDetailComponent }    from './pages/track-detail/track-detail.component';
import { ContractConfigComponent } from './pages/contract-config/contract-config.component';
import { WalletComponent }         from './pages/wallet/wallet.component';
import { RegisterComponent }        from './pages/auth/register/register.component';
import { OauthCallbackComponent }   from './pages/auth/oauth-callback/oauth-callback.component';
import { CompleteProfileComponent } from './pages/auth/complete-profile/complete-profile.component';
import { SelectRoleComponent }           from './pages/auth/select-role/select-role.component';
import { SubmitMixmasterSampleComponent } from './pages/auth/submit-mixmaster-sample/submit-mixmaster-sample.component';
import { ProfileComponent }       from './pages/profile/profile.component';
import { EditProfileComponent }   from './pages/profile/edit-profile/edit-profile.component';
import { EditSecurityComponent }  from './pages/profile/edit-security/edit-security.component';
import { NotificationsComponent } from './pages/notifications/notifications.component';
import { ContactComponent }                   from './pages/contact/contact.component';
import { DashboardBeatmakerComponent }        from './pages/dashboard/dashboard-beatmaker/dashboard-beatmaker.component';
import { DashboardArtistComponent }           from './pages/dashboard/dashboard-artist/dashboard-artist.component';
import { DashboardMixEngineerComponent }      from './pages/dashboard/dashboard-mix-engineer/dashboard-mix-engineer.component';
import { PurchasesComponent }                 from './pages/purchases/purchases.component';
import { MixmasterEngineersComponent }        from './pages/mixmaster/engineers/engineers.component';
import { MixmasterOrderComponent }            from './pages/mixmaster/order/order.component';
import { MixPaymentSuccessComponent }         from './pages/mixmaster/payment-success/payment-success.component';

export const routes: Routes = [
  { path: '',                              component: HomeComponent },
  { path: 'upload-track',                  component: UploadTrackComponent },
  { path: 'login',                         component: LoginComponent },
  { path: 'register',                      component: RegisterComponent },
  { path: 'oauth-callback',                component: OauthCallbackComponent },
  { path: 'complete-profile',              component: CompleteProfileComponent },
  { path: 'select-role',                   component: SelectRoleComponent },
  { path: 'track/:id',                     component: TrackDetailComponent },
  { path: 'contract/:trackId/:format',     component: ContractConfigComponent },
  { path: 'wallet',                        component: WalletComponent },
  { path: 'submit-sample',                 component: SubmitMixmasterSampleComponent },
  { path: 'profile/edit',                  component: EditProfileComponent },
  { path: 'profile/security',              component: EditSecurityComponent },
  { path: 'profile/:username',             component: ProfileComponent },
  { path: 'notifications',                 component: NotificationsComponent },
  { path: 'contact',                       component: ContactComponent },
  { path: 'dashboard/beatmaker',           component: DashboardBeatmakerComponent },
  { path: 'dashboard/artist',              component: DashboardArtistComponent },
  { path: 'dashboard/mix-engineer',        component: DashboardMixEngineerComponent },
  { path: 'purchases',                     component: PurchasesComponent },
  { path: 'mix/engineers',                 component: MixmasterEngineersComponent },
  { path: 'mix/order/:engineerId',         component: MixmasterOrderComponent },
  { path: 'mix/payment-success',           component: MixPaymentSuccessComponent },
];
